--------------------------------------------------------
-- Archivo creado  - jueves-enero-16-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CAT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABACERIA"."CAT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COM_PROV_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABACERIA"."COM_PROV_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FAC_CAB_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABACERIA"."FAC_CAB_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 39 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FAC_DET_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABACERIA"."FAC_DET_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABACERIA"."PER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABACERIA"."PRO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ABA_CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "ABACERIA"."ABA_CATEGORIAS" 
   (	"CAT_ID" NUMBER(4,0), 
	"CAT_NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ABACERIA"."ABA_CATEGORIAS"."CAT_ID" IS 'identificador numerico unico de la categoria';
   COMMENT ON COLUMN "ABACERIA"."ABA_CATEGORIAS"."CAT_NOMBRE" IS 'nombre de una categoria de productos
ejm: alimentos, bebidas';
--------------------------------------------------------
--  DDL for Table ABA_COMPRAS_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" 
   (	"COM_PROV_ID" NUMBER(7,0), 
	"COM_PROV_FECHA" DATE, 
	"COM_PROV_CANTIDAD" NUMBER(4,0), 
	"ABA_PRODUCTOS_PRO_ID" NUMBER(7,0), 
	"ABA_PERSONAS_PER_ID" NUMBER(8,0), 
	"COM_PROV_NUMERO_FACTURA" NUMBER(7,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ABACERIA"."ABA_COMPRAS_PROVEEDOR"."COM_PROV_ID" IS 'identificador numerico unico de la compra que se le hace a un proveedor';
   COMMENT ON COLUMN "ABACERIA"."ABA_COMPRAS_PROVEEDOR"."COM_PROV_FECHA" IS 'fecha en la que se compraron productos al proveedor';
   COMMENT ON COLUMN "ABACERIA"."ABA_COMPRAS_PROVEEDOR"."COM_PROV_CANTIDAD" IS 'cantidad comprada de determinado producto';
   COMMENT ON COLUMN "ABACERIA"."ABA_COMPRAS_PROVEEDOR"."ABA_PRODUCTOS_PRO_ID" IS 'codigo numerico de producto que proveedor suministra a abaceria';
   COMMENT ON COLUMN "ABACERIA"."ABA_COMPRAS_PROVEEDOR"."ABA_PERSONAS_PER_ID" IS 'identificador de persona (proveedor) que entrega el producto';
   COMMENT ON COLUMN "ABACERIA"."ABA_COMPRAS_PROVEEDOR"."COM_PROV_NUMERO_FACTURA" IS 'numero de factura del proveedor correspondiente a nuestra compra';
--------------------------------------------------------
--  DDL for Table ABA_FACTURAS_CABECERA
--------------------------------------------------------

  CREATE TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" 
   (	"FAC_CAB_ID" NUMBER(7,0), 
	"FAC_CAB_ESTADO" CHAR(1 BYTE), 
	"FAC_CAB_FECHA" DATE, 
	"FAC_CAB_SUBTOTAL" NUMBER(6,2), 
	"FAC_CAB_IVA" NUMBER(5,2), 
	"FAC_CAB_TOTAL" NUMBER(6,2), 
	"ABA_PERSONAS_PER_ID1" NUMBER(8,0), 
	"ABA_PERSONAS_PER_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."FAC_CAB_ID" IS 'identificador numerico unico de la factura';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."FAC_CAB_ESTADO" IS 'true si la factura esta activa
false si se anulo';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."FAC_CAB_FECHA" IS 'fecha en  la que se emite la factura';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."FAC_CAB_SUBTOTAL" IS 'precio de la compra sin iva';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."FAC_CAB_IVA" IS 'valor de recargo por iva';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."FAC_CAB_TOTAL" IS 'total pagado por la compra (incluye iva)';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."ABA_PERSONAS_PER_ID1" IS 'identificador numerico del cliente al que le pertenece la factura';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_CABECERA"."ABA_PERSONAS_PER_ID" IS 'identificador numerico del empleado que realizo la factura';
--------------------------------------------------------
--  DDL for Table ABA_FACTURAS_DETALLE
--------------------------------------------------------

  CREATE TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" 
   (	"FAC_DET_ID" NUMBER(8,0), 
	"FAC_CAB_ID" NUMBER(7,0), 
	"ABA_PRODUCTOS_PRO_ID" NUMBER(7,0), 
	"FAC_DET_CANTIDAD" NUMBER(4,0), 
	"FAC_DET_SUBTOTAL" NUMBER(6,2), 
	"FAC_DET_IVA" NUMBER(5,2), 
	"FAC_DET_TOTAL" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_DETALLE"."FAC_DET_ID" IS 'identificador numerico unico del detalle de factura';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_DETALLE"."FAC_CAB_ID" IS 'identificador numerico de la factura que le corresponde este detalle';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_DETALLE"."ABA_PRODUCTOS_PRO_ID" IS 'identificador numerico del producto al que le corresponde el detalle';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_DETALLE"."FAC_DET_CANTIDAD" IS 'cantidad de producto adquirida';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_DETALLE"."FAC_DET_SUBTOTAL" IS 'precio del/los productos sin iva';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_DETALLE"."FAC_DET_IVA" IS 'recargo de iva';
   COMMENT ON COLUMN "ABACERIA"."ABA_FACTURAS_DETALLE"."FAC_DET_TOTAL" IS 'total del/los productos';
--------------------------------------------------------
--  DDL for Table ABA_PERSONAS
--------------------------------------------------------

  CREATE TABLE "ABACERIA"."ABA_PERSONAS" 
   (	"PER_ID" NUMBER(8,0), 
	"PER_TIPO_ADMINISTRADOR" CHAR(1 BYTE), 
	"PER_CEDULA" VARCHAR2(10 BYTE), 
	"PER_NOMBRE" VARCHAR2(50 BYTE), 
	"PER_APELLIDO" VARCHAR2(50 BYTE), 
	"PER_DIRECCION" VARCHAR2(100 BYTE), 
	"PER_TELEFONO" VARCHAR2(10 BYTE), 
	"PER_CELULAR" VARCHAR2(10 BYTE), 
	"PER_USUARIO" VARCHAR2(25 BYTE), 
	"PER_CONTRASENIA" VARCHAR2(25 BYTE), 
	"PER_ACTIVO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_ID" IS 'codigo numerico unico de persona registrada';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_TIPO_ADMINISTRADOR" IS '1 si es un empleado administrador
0  si es un empleado cajero';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_CEDULA" IS 'cedula de persona';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_NOMBRE" IS 'nombre o nombres de persona';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_APELLIDO" IS 'apellidos de persona';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_DIRECCION" IS 'direccion completa de la persona';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_TELEFONO" IS 'telefono convencional de persona';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_CELULAR" IS 'numero de celular de persona';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_USUARIO" IS 'Solo en caso de ser empleador: Usuario unico  para que empleado de la abaceria pueda acceder a sistema, ejm: Juan98';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_CONTRASENIA" IS 'Solo en caso de ser empleado: Contrasenia para que empleado de la abaceria pueda acceder a sistema';
   COMMENT ON COLUMN "ABACERIA"."ABA_PERSONAS"."PER_ACTIVO" IS 'true (si el empleado tiene una cuenta activa / cliente esta activo)
false (si el empleado no esta activo / cliente no esta activo)';
--------------------------------------------------------
--  DDL for Table ABA_PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "ABACERIA"."ABA_PRODUCTOS" 
   (	"PRO_ID" NUMBER(7,0), 
	"ABA_CATEGORIAS_CAT_ID" NUMBER(4,0), 
	"PRO_DESCRIPCION" VARCHAR2(50 BYTE), 
	"PRO_STOCK" NUMBER(7,0), 
	"PRO_TIENE_IVA" CHAR(1 BYTE), 
	"PRO_NACIONAL" CHAR(1 BYTE), 
	"PRO_UNIDAD_MEDIDA" VARCHAR2(50 BYTE), 
	"PRO_PRECIO" NUMBER(5,2), 
	"PRO_CODIGO_BARRAS" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_ID" IS 'identificador numerico unico del producto';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."ABA_CATEGORIAS_CAT_ID" IS 'codigo numerico de la categoria que le corresponde al producto';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_DESCRIPCION" IS 'nombre del producto adquirido ejm: Arroz';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_STOCK" IS 'cantidad que se dispone del producto';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_TIENE_IVA" IS 'true si tiene iva
false si no tiene iva';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_NACIONAL" IS 'true si es nacional
false si no es nacional';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_UNIDAD_MEDIDA" IS 'unidad en la que se vende el producto ejm: unidades, cajas, kilos';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_PRECIO" IS 'precio del producto (sin recargo de iva)';
   COMMENT ON COLUMN "ABACERIA"."ABA_PRODUCTOS"."PRO_CODIGO_BARRAS" IS 'codigo de barras para poder encontrar un producto rapidamente';
REM INSERTING into ABACERIA.ABA_CATEGORIAS
SET DEFINE OFF;
Insert into ABACERIA.ABA_CATEGORIAS (CAT_ID,CAT_NOMBRE) values ('1','bebidas');
Insert into ABACERIA.ABA_CATEGORIAS (CAT_ID,CAT_NOMBRE) values ('2','alimentos');
Insert into ABACERIA.ABA_CATEGORIAS (CAT_ID,CAT_NOMBRE) values ('3','granos');
REM INSERTING into ABACERIA.ABA_COMPRAS_PROVEEDOR
SET DEFINE OFF;
REM INSERTING into ABACERIA.ABA_FACTURAS_CABECERA
SET DEFINE OFF;
Insert into ABACERIA.ABA_FACTURAS_CABECERA (FAC_CAB_ID,FAC_CAB_ESTADO,FAC_CAB_FECHA,FAC_CAB_SUBTOTAL,FAC_CAB_IVA,FAC_CAB_TOTAL,ABA_PERSONAS_PER_ID1,ABA_PERSONAS_PER_ID) values ('38','1',to_date('16/01/2020','DD/MM/RRRR'),'120','3,36','123,36','3','2');
Insert into ABACERIA.ABA_FACTURAS_CABECERA (FAC_CAB_ID,FAC_CAB_ESTADO,FAC_CAB_FECHA,FAC_CAB_SUBTOTAL,FAC_CAB_IVA,FAC_CAB_TOTAL,ABA_PERSONAS_PER_ID1,ABA_PERSONAS_PER_ID) values ('37','1',to_date('16/01/2020','DD/MM/RRRR'),'24,5','2,94','27,44','3','2');
REM INSERTING into ABACERIA.ABA_FACTURAS_DETALLE
SET DEFINE OFF;
Insert into ABACERIA.ABA_FACTURAS_DETALLE (FAC_DET_ID,FAC_CAB_ID,ABA_PRODUCTOS_PRO_ID,FAC_DET_CANTIDAD,FAC_DET_SUBTOTAL,FAC_DET_IVA,FAC_DET_TOTAL) values ('5','38','3','8','28','3,36','31,36');
Insert into ABACERIA.ABA_FACTURAS_DETALLE (FAC_DET_ID,FAC_CAB_ID,ABA_PRODUCTOS_PRO_ID,FAC_DET_CANTIDAD,FAC_DET_SUBTOTAL,FAC_DET_IVA,FAC_DET_TOTAL) values ('6','38','2','4','92','0','92');
Insert into ABACERIA.ABA_FACTURAS_DETALLE (FAC_DET_ID,FAC_CAB_ID,ABA_PRODUCTOS_PRO_ID,FAC_DET_CANTIDAD,FAC_DET_SUBTOTAL,FAC_DET_IVA,FAC_DET_TOTAL) values ('4','37','3','7','24,5','2,94','27,44');
REM INSERTING into ABACERIA.ABA_PERSONAS
SET DEFINE OFF;
Insert into ABACERIA.ABA_PERSONAS (PER_ID,PER_TIPO_ADMINISTRADOR,PER_CEDULA,PER_NOMBRE,PER_APELLIDO,PER_DIRECCION,PER_TELEFONO,PER_CELULAR,PER_USUARIO,PER_CONTRASENIA,PER_ACTIVO) values ('3','1','1','e','o','Cuenca','123','121','1','1','1');
Insert into ABACERIA.ABA_PERSONAS (PER_ID,PER_TIPO_ADMINISTRADOR,PER_CEDULA,PER_NOMBRE,PER_APELLIDO,PER_DIRECCION,PER_TELEFONO,PER_CELULAR,PER_USUARIO,PER_CONTRASENIA,PER_ACTIVO) values ('1',null,'0106073331','Eduardo','Ayora','Cuenca','3012113','0984709259',null,null,'1');
Insert into ABACERIA.ABA_PERSONAS (PER_ID,PER_TIPO_ADMINISTRADOR,PER_CEDULA,PER_NOMBRE,PER_APELLIDO,PER_DIRECCION,PER_TELEFONO,PER_CELULAR,PER_USUARIO,PER_CONTRASENIA,PER_ACTIVO) values ('2','0','0106073332','Antonio','Ochoa','cuenca','3012114','0984709258','AntonioOchoa','123','1');
REM INSERTING into ABACERIA.ABA_PRODUCTOS
SET DEFINE OFF;
Insert into ABACERIA.ABA_PRODUCTOS (PRO_ID,ABA_CATEGORIAS_CAT_ID,PRO_DESCRIPCION,PRO_STOCK,PRO_TIENE_IVA,PRO_NACIONAL,PRO_UNIDAD_MEDIDA,PRO_PRECIO,PRO_CODIGO_BARRAS) values ('2','1','ere','36','0','1','libra','23','36');
Insert into ABACERIA.ABA_PRODUCTOS (PRO_ID,ABA_CATEGORIAS_CAT_ID,PRO_DESCRIPCION,PRO_STOCK,PRO_TIENE_IVA,PRO_NACIONAL,PRO_UNIDAD_MEDIDA,PRO_PRECIO,PRO_CODIGO_BARRAS) values ('3','2','helado','32','1','1','unidad','3,5','32');
--------------------------------------------------------
--  DDL for Index ABA_CATEGORIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABACERIA"."ABA_CATEGORIAS_PK" ON "ABACERIA"."ABA_CATEGORIAS" ("CAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ABA_COMPRAS_PROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABACERIA"."ABA_COMPRAS_PROVEEDOR_PK" ON "ABACERIA"."ABA_COMPRAS_PROVEEDOR" ("COM_PROV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ABA_FACTURAS_CABECERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABACERIA"."ABA_FACTURAS_CABECERA_PK" ON "ABACERIA"."ABA_FACTURAS_CABECERA" ("FAC_CAB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ABA_FACTURAS_DETALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABACERIA"."ABA_FACTURAS_DETALLE_PK" ON "ABACERIA"."ABA_FACTURAS_DETALLE" ("FAC_DET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ABA_PERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABACERIA"."ABA_PERSONAS_PK" ON "ABACERIA"."ABA_PERSONAS" ("PER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ABA_PRODUCTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABACERIA"."ABA_PRODUCTOS_PK" ON "ABACERIA"."ABA_PRODUCTOS" ("PRO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ABA_CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_CATEGORIAS" MODIFY ("CAT_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_CATEGORIAS" MODIFY ("CAT_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_CATEGORIAS" ADD CONSTRAINT "ABA_CATEGORIAS_PK" PRIMARY KEY ("CAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ABA_COMPRAS_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" MODIFY ("COM_PROV_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" MODIFY ("COM_PROV_FECHA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" MODIFY ("COM_PROV_CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" MODIFY ("ABA_PRODUCTOS_PRO_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" MODIFY ("ABA_PERSONAS_PER_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" MODIFY ("COM_PROV_NUMERO_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" ADD CONSTRAINT "ABA_COMPRAS_PROVEEDOR_PK" PRIMARY KEY ("COM_PROV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ABA_FACTURAS_CABECERA
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("FAC_CAB_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("FAC_CAB_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("FAC_CAB_FECHA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("FAC_CAB_SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("FAC_CAB_IVA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("FAC_CAB_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("ABA_PERSONAS_PER_ID1" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" MODIFY ("ABA_PERSONAS_PER_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" ADD CONSTRAINT "ABA_FACTURAS_CABECERA_PK" PRIMARY KEY ("FAC_CAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ABA_FACTURAS_DETALLE
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" MODIFY ("FAC_DET_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" MODIFY ("FAC_CAB_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" MODIFY ("ABA_PRODUCTOS_PRO_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" MODIFY ("FAC_DET_CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" MODIFY ("FAC_DET_SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" MODIFY ("FAC_DET_IVA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" MODIFY ("FAC_DET_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" ADD CONSTRAINT "ABA_FACTURAS_DETALLE_PK" PRIMARY KEY ("FAC_DET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ABA_PERSONAS
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_PERSONAS" MODIFY ("PER_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PERSONAS" MODIFY ("PER_CEDULA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PERSONAS" MODIFY ("PER_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PERSONAS" MODIFY ("PER_APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PERSONAS" ADD CONSTRAINT "ABA_PERSONAS_PK" PRIMARY KEY ("PER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ABA_PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("PRO_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("ABA_CATEGORIAS_CAT_ID" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("PRO_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("PRO_STOCK" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("PRO_TIENE_IVA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("PRO_NACIONAL" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("PRO_UNIDAD_MEDIDA" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" MODIFY ("PRO_PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" ADD CONSTRAINT "ABA_PRODUCTOS_PK" PRIMARY KEY ("PRO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABA_COMPRAS_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" ADD CONSTRAINT "COM_PROV_PER_FK" FOREIGN KEY ("ABA_PERSONAS_PER_ID")
	  REFERENCES "ABACERIA"."ABA_PERSONAS" ("PER_ID") ENABLE;
  ALTER TABLE "ABACERIA"."ABA_COMPRAS_PROVEEDOR" ADD CONSTRAINT "COM_PROV_PRO_FK" FOREIGN KEY ("ABA_PRODUCTOS_PRO_ID")
	  REFERENCES "ABACERIA"."ABA_PRODUCTOS" ("PRO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABA_FACTURAS_CABECERA
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" ADD CONSTRAINT "FAC_CAB_PER_FK" FOREIGN KEY ("ABA_PERSONAS_PER_ID")
	  REFERENCES "ABACERIA"."ABA_PERSONAS" ("PER_ID") ENABLE;
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_CABECERA" ADD CONSTRAINT "FAC_CAB_PER_FKV2" FOREIGN KEY ("ABA_PERSONAS_PER_ID1")
	  REFERENCES "ABACERIA"."ABA_PERSONAS" ("PER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABA_FACTURAS_DETALLE
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" ADD CONSTRAINT "FAC_DET_FAC_CAB_FK" FOREIGN KEY ("FAC_CAB_ID")
	  REFERENCES "ABACERIA"."ABA_FACTURAS_CABECERA" ("FAC_CAB_ID") ENABLE;
  ALTER TABLE "ABACERIA"."ABA_FACTURAS_DETALLE" ADD CONSTRAINT "FAC_DET_PRO_FK" FOREIGN KEY ("ABA_PRODUCTOS_PRO_ID")
	  REFERENCES "ABACERIA"."ABA_PRODUCTOS" ("PRO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABA_PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ABACERIA"."ABA_PRODUCTOS" ADD CONSTRAINT "PRO_CAT_FK" FOREIGN KEY ("ABA_CATEGORIAS_CAT_ID")
	  REFERENCES "ABACERIA"."ABA_CATEGORIAS" ("CAT_ID") ENABLE;
