
import java.awt.BorderLayout;
import javax.swing.JDesktopPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paùl Arias
 */
public class VistaEmpleado extends javax.swing.JFrame {
    private JDesktopPane escritorio;
    private RegistroCliente rc= new RegistroCliente();
    private Factura fac=new Factura();
    
    /**
     * Creates new form VistaEmpleado
     */
    public VistaEmpleado() {
        initComponents();
        
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        ClienteJmenu = new javax.swing.JMenu();
        RegistroClienteMI = new javax.swing.JMenuItem();
        FacturaJmenu = new javax.swing.JMenu();
        AgregarFacturaMI = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClienteJmenu.setText("Cliente");

        RegistroClienteMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro cliente.jpg"))); // NOI18N
        RegistroClienteMI.setText("Registro de Cliente");
        RegistroClienteMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroClienteMIActionPerformed(evt);
            }
        });
        ClienteJmenu.add(RegistroClienteMI);

        jMenuBar1.add(ClienteJmenu);

        FacturaJmenu.setText("Factura");

        AgregarFacturaMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.jpg"))); // NOI18N
        AgregarFacturaMI.setText("Agregar Factura");
        AgregarFacturaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFacturaMIActionPerformed(evt);
            }
        });
        FacturaJmenu.add(AgregarFacturaMI);

        jMenuBar1.add(FacturaJmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void RegistroClienteMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroClienteMIActionPerformed
      if(rc.isShowing()){
		System.out.println("error");
	}
	else {
		rc.setVisible(true);
		escritorio.add(rc);
	}try {
		rc.setSelected(true);
	} catch (Exception e) {			
		e.printStackTrace();
    }//GEN-LAST:event_RegistroClienteMIActionPerformed
    }
    private void AgregarFacturaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFacturaMIActionPerformed
        if(fac.isShowing()){
		System.out.println("error");
	}
	else {
		fac.setVisible(true);
		escritorio.add(fac);
	}try {
		fac.setSelected(true);
	} catch (Exception e) {			
		e.printStackTrace();
        }
    }//GEN-LAST:event_AgregarFacturaMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarFacturaMI;
    private javax.swing.JMenu ClienteJmenu;
    private javax.swing.JMenu FacturaJmenu;
    private javax.swing.JMenuItem RegistroClienteMI;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables

}
